repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -    id: check-ast
    -    id: check-merge-conflict
    -    id: detect-private-key
    -    id: check-xml
    -    id: end-of-file-fixer
    -    id: trailing-whitespace

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language: python
        files: \.py$
        entry: flake8
        additional_dependencies: [wemake-python-styleguide==0.16.1]

-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        entry: isort
        files: \.py$
        verbose: true
        args: ["--df", "-c"]
        exclude: __init__.py

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -    id: forbid-tabs
    -    id: remove-tabs
