version: "3"

services:
  web: &web
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    tty: true
    stdin_open: true
    env_file:
      - project.env
    environment:
      # DEV
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
    ports:
      - 8000:8000
    depends_on:
      - db
      - wdb
    volumes:
      - "./mysite:/mysite"

  autotests:
    <<: *web
    command: ["python", "manage.py", "test", "-v", "2"]

  db:
    image: postgres:15
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-hisotry:/root


  # DEV
  wdb:
    image: kozea/wdb:3.2.5
    ports:
      - 1984:1984

volumes:
  postgres-data:
  postgres-hisotry:
