version: "3"

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    tty: true
    stdin_open: true
    env_file:
      - project.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - "./mysite:/mysite"

  db:
    image: postgres:15
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
